In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [3]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true,y_predicted):
        total_error+= abs(yt-yp)
    print("Total error: ",total_error)
    
    mae = total_error/ len(y_predicted)
    print("MAE", mae)
    return mae

In [4]:
mae(y_true, y_predicted)

Total error:  2.5
MAE 0.5


0.5

In [5]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [6]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [7]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [10]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [14]:
np.log(2)

0.6931471805599453

In [18]:
np.square(y_predicted - y_true)

array([0.49, 0.09, 1.  , 0.  , 0.25])

In [19]:
np.mean(np.square(y_predicted - y_true))

0.366

In [20]:
np.square(2)

4

In [24]:
epsilon = 1e-15

In [25]:
print(epsilon)

1e-15
